application: gvoice-sip-status
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /refresh
  script: refresh.py
  login: admin

- url: .*
  script: main.py

